language: java
jdk:
  - oraclejdk8
install: "pip install PyYAML"
script: 
  - ant compile
  - python test.py
  - ant clean
notifications:
  email:
    on_success: change # [always|never|change]
    on_failure: change # [always|never|change]