language: java

jdk:
  - oraclejdk8

install: "sudo pip install PyYAML"

script: 
  - ant compile
  - python test.py
  - ant clean
  
notifications:
  email:
    on_success: change # [always|never|change]
    on_failure: change # [always|never|change]
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/96ae2762bdc276ba0c3a
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
