language: java

jdk:
  - oraclejdk8

install: "sudo pip install PyYAML"

script: 
  - ant compile
  - cd tests
  - python test.py
  - cd ..
  - ant clean
  
notifications:
  email:
    on_success: change # [always|never|change]
    on_failure: change # [always|never|change]
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/127500ab5e6b7cbcfd8c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
